import './index.scss';
import './custom-elements/AdminConfigurationElement';
import './custom-elements/AppElement';
import './custom-elements/LoginElement';
import './custom-elements/ManageSubscriptionsElement';
import './custom-elements/ManageUsersElement';
import './custom-elements/OpenTicketElement';
import './custom-elements/SubscriptionFormElement';
import './local/LocalAppElement';
